publishDir = "../sherlockes.github.io"
baseurl = "/"
title = "Sherblog"
languageCode = "es"
DefaultContentLanguage = "es"
paginate = "5" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
    name = "Sherlockes"
    bio = "Solo un discípulo de San Google..."
    avatar = "img/avatar.png"

[permalinks]
    post = "/:title/"

[Params]
  subtitle = "Sólo mi forma de hacer las cosas..."
  description = "Un poco de informática, bricolaje, bicicleta y todos los problemas que se me ponen delante en el día a día no está de más documentarlos, a alguien le puede ayudar..."
  #copyright = "Sherlockes@2019" #
  opengraph = true
  twitter_cards = true
  readmore = false
  authorbox = false
  disable_comments = true
  toc = true
  post_navigation = true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["post"]
  dateformat = "2006-01-02"
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages

  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 10 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "sherblogpro"
  telegram = "sherlockes"
  github = "sherlockes"
  youtube = "UCkx4Zgs1ujSuVsxcOFuGCoQ"
  strava = "11156844"
